//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeilaoStatusWebService.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Leilao
    {
        public int LeilaoID { get; set; }
        public string Natureza { get; set; }
        public string Forma { get; set; }
        public System.DateTime DataDeInicio { get; set; }
        public System.DateTime DataDeFim { get; set; }
        public double LanceMinimo { get; set; }
        public double LanceMaximo { get; set; }
        [JsonIgnore]
        public Nullable<int> Lote_LoteID { get; set; }
        [JsonIgnore]
        public Nullable<int> Usuario_UsuarioID { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
